- README.md
**Description:**
- edit readme
> feat: edit readme

- backend/README.md
> feat: readme update

- backend/README.md
> feat:second readme update

- frontend/package.json
- frontend/src/App.tsx
- frontend/src/configs/index.tsx
- frontend/src/configs/routes.ts
- frontend/src/index.tsx
- frontend/src/pages/admin/home.tsx
- frontend/yarn.lock
- add setup with react router dom and add antdesign for admin page
- #11 
**Memo:**
- none
> feat: add setup with react router dom and add antdesign for admin page

- frontend/package.json
- frontend/src/configs/routes.ts
- frontend/src/pages/admin/home.tsx
- frontend/src/pages/admin/styles.module.scss
- frontend/src/pages/client/home.tsx
- frontend/src/typings/declarations.d.ts
- frontend/yarn.lock
- add layout of admin
- route seperation
- node-sass setting
- #16 
**Memo:**
- none
> feat: add layout of admin page and  node-sass setting , route seperation

- README.md
- backend/capstone/src/main/java/com/capstone/controller/AdminContentsController.java
- backend/capstone/src/main/java/com/capstone/controller/AdminUserController.java
- backend/capstone/src/main/java/com/capstone/controller/ContentsNotFoundException.java
- backend/capstone/src/main/java/com/capstone/dao/EquipmentDao.java
- backend/capstone/src/main/java/com/capstone/dao/HomeTrainingDao.java
- backend/capstone/src/main/java/com/capstone/dao/MealDao.java
- backend/capstone/src/main/java/com/capstone/dao/UserDao.java
-rename incorrect class name
-add exception class for contents not found exception
**Memo:**
- none
> Error correcting

- backend/capstone/src/main/java/com/capstone/dao/MealDao.java
- backend/capstone/src/main/java/com/capstone/dao/UserDao.java
- backend/capstone/src/main/java/com/capstone/model/Meal.java
- backend/capstone/src/main/java/com/capstone/model/User.java
- backend/capstone/src/main/java/com/capstone/repository/MealRepository.java
add jpa to meal part / only get message
**Memo:**
- none
> add jpa to meal part / only get message

- backend/README.md
- delete useless readme
- none
**Memo:**
- none
> feat: delete useless readme

- frontend/.env
- frontend/package.json
- frontend/src/apis/admin.ts
- frontend/src/apis/index.ts
- frontend/src/pages/admin/home.tsx
- frontend/yarn.lock
> feat: add api feature

- backend/capstone/src/main/java/com/capstone/controller/AdminContentsController.java
- frontend/src/__MOCK__/mock.tsx
- frontend/src/apis/admin.ts
- frontend/src/components/admin/RecommendManageTable/index.tsx
- frontend/src/pages/admin/home.tsx
- map api response to admin UI
- NONE
**Memo:**
> feat: map api response to admin UI

- backend/capstone/src/main/java/com/capstone/model/Equipment.java
- frontend/src/__MOCK__/mock.tsx
- add api mapping to equipment
- https://github.com/covid19-cau/capstone-design-project/issues/18
**Memo:**
> feat: add api mapping to equipment

- frontend/src/__MOCK__/mock.tsx
- frontend/src/apis/admin.ts
- frontend/src/components/admin/ContentsModal/index.tsx
- frontend/src/components/admin/RecommendManageTable/index.tsx
- frontend/src/pages/admin/home.tsx
- register contents (api mapping)
- #18 
**Memo:**
> feat: add register contents features

- backend/capstone/src/main/java/com/capstone/controller/AdminContentsController.java
- backend/capstone/src/main/java/com/capstone/controller/AdminMemberController.java
- backend/capstone/src/main/java/com/capstone/repository/EquipmentRepository.java
- backend/capstone/src/main/java/com/capstone/repository/MealRepository.java
- backend/capstone/src/main/java/com/capstone/repository/MemberRepository.java
- backend/capstone/src/main/java/com/capstone/repository/RecordRepository.java
- backend/capstone/src/main/java/com/capstone/repository/VideoRepository.java
- deal with error
- none
**Memo:**
- none
> feat: update repository deal with error

- frontend/src/apis/admin.ts
- frontend/src/components/admin/RecommendManageTable/index.tsx
- frontend/src/components/admin/UserExpandRender/index.tsx
- frontend/src/data/index.tsx
- frontend/src/pages/admin/home.tsx
- add mapping user data
- #19 
**Memo:**
> feat: mapping user data

- frontend/src/apis/admin.ts
- frontend/src/components/admin/RecommendManageTable/index.tsx
- frontend/src/pages/admin/home.tsx
- update api mapping
#18 
**Memo:**
> feat: update api mapping

- frontend/src/apis/admin.ts
- frontend/src/components/admin/RecommendManageTable/index.tsx
- frontend/src/data/index.tsx
- frontend/src/pages/admin/home.tsx
- delete contents feature with api
- #18 
**Memo:**
> feat: delete contents feature with api

- backend/capstone/src/main/java/com/capstone/controller/AdminUserController.java
- backend/capstone/src/main/java/com/capstone/controller/RegisterController.java
- backend/capstone/src/main/java/com/capstone/controller/UserServiceController.java
- backend/capstone/src/main/java/com/capstone/dao/UserDao.java
- backend/capstone/src/main/java/com/capstone/model/Challenge.java
- backend/capstone/src/main/java/com/capstone/model/Member.java
- backend/capstone/src/main/java/com/capstone/service/AuthenticationService.java
- backend/capstone/src/main/java/com/capstone/service/RecommendSet.java
- backend/capstone/src/main/java/com/capstone/service/UserService.java
set 'get challenge and get recommend contents' function frame
[55](https://github.com/covid19-cau/capstone-design-project/issues/55)
**Memo:**
- none
> /feature. set 'get challenge and get recommend contents' function frame

- backend/capstone/src/main/java/com/capstone/model/Challenge.java
- backend/capstone/src/main/java/com/capstone/model/Member.java
- backend/capstone/src/main/java/com/capstone/model/Record.java
- modify catalog and modify database
- none
**Memo:**
- none
> merge Schema

- frontend/src/assets/check-box.svg
- frontend/src/components/client/organisms/navBar/index.tsx
- frontend/src/configs/routes.ts
- frontend/src/index.style.scss
- frontend/src/index.tsx
- frontend/src/pages/client/Signin/index.tsx
- frontend/src/pages/client/Signin/styles.module.scss
- frontend/src/pages/client/Signup/index.tsx
- frontend/src/pages/client/Signup/styles.module.scss
- add signin, signup UI
- add font style
- #66  
**Memo:**
> feat: add Login, signup UI

- README.md
> /delete validation in temp

- frontend/package.json
- frontend/src/apis/client.ts
- frontend/src/components/client/organisms/navBar/index.tsx
- frontend/src/components/client/organisms/navBar/styles.module.scss
- frontend/src/pages/client/Signin/index.tsx
- frontend/src/pages/client/Signup/index.tsx
- frontend/yarn.lock
- api integration with login api
- api integration with signup api
**Memo:**
- none
> feat: add login and signup api integration

- frontend/package.json
- frontend/src/components/client/molecules/Card/styles.module.scss
- frontend/src/components/client/organisms/TitledContents/index.tsx
- frontend/src/components/client/organisms/TitledContents/style.module.scss
- frontend/src/pages/client/home.tsx
- frontend/src/types.d.ts
- frontend/yarn.lock
- get thumbnail from youtube url and add ui for this.
**Memo:**
> feat: get thumbnail from youtube video

- backend/capstone/src/main/java/com/capstone/controller/RegisterController.java
- backend/capstone/src/main/java/com/capstone/controller/UserServiceController.java
- backend/capstone/src/main/java/com/capstone/dao/EquipmentDao.java
- backend/capstone/src/main/java/com/capstone/dao/MealDao.java
- backend/capstone/src/main/java/com/capstone/model/Equipment.java
- backend/capstone/src/main/java/com/capstone/model/Meal.java
- backend/capstone/src/main/java/com/capstone/model/Video.java
- backend/capstone/src/main/java/com/capstone/repository/MealRepository.java
- backend/capstone/src/main/java/com/capstone/repository/VideoRepository.java
- backend/capstone/src/main/java/com/capstone/service/UserService.java
> /when login, get token and member_id

- backend/capstone/src/main/java/com/capstone/dao/MealDao.java
- backend/capstone/src/main/java/com/capstone/model/Challenge.java
- backend/capstone/src/main/java/com/capstone/model/Equipment.java
- backend/capstone/src/main/java/com/capstone/model/Meal.java
- backend/capstone/src/main/java/com/capstone/model/Video.java
- Capital letters and underbars were coordinated.
- none
**Memo:**
- none
> (modifyed) rename Data
